format = """
$directory\
$git_branch\
$git_status\
$git_state\
$kubernetes\
$line_break\
$python\
$character"""

[directory]
style = 'dimmed purple'

[character]
success_symbol = '[❯](dimmed green)'
error_symbol = '[❯](dimmed red)'
vimcmd_symbol = '[❮](dimmed green)'

[git_branch]
format = '[$branch]($style) '
style = 'dimmed green'

[git_status]
format = '([\($all_status$ahead_behind\)]($style) )'
style = 'dimmed green'

[git_state]
format = '(\([$state($progress_current/$progress_total)]($style)\) )'
style = 'dimmed green'

[kubernetes]
format = '[$context]($style)( [\($namespace\)]($style)) '
style = 'dimmed blue'
disabled = false
contexts = [
  { context_pattern = "gke_ncb-dev-project_asia-south1_ncb-dev-cluster", context_alias = "ncb-dev"},
]

[python]
format = '([$virtualenv]($style) )'
style = 'bright-black'
